### ISSUE TITLE
디렉토리 구조 설정

### ISSUE THREAD

**Issue by algo2000** [belf-kr/front-server#21]
next 프로젝트 디렉토리 구조를 잡습니다

**Comment by parkgang** [comment]
@algo2000 디렉터리 구조는 어떻게 가져가실 생각인가요? 개인적으로 아래의 구조를 추천합니다.
1. components
    1. 컴포넌트 단위로 디렉터리를 생성합니다.
    2. 디렉터리에 index.tsx 파일이 반드시 존재하며 default component 역할을 합니다.
    3. 굳이 `components/{컴포넌트 이름}/index.tsx` 으로 가져가는 이유는 컴포넌트만을 위한 함수 혹은 테스트 코드 및 스타일을 한곳에 모을 수 있기 때문입니다.
1. hooks
    1. 모든 커스텀 훅이 들어감
1. libs
    1. api 타입 정의 등 helper 시리즈 코드가 들어감
1. pages
   1. 컴포넌트를 모아서 외부로 노출되는 page
1. states
   1. recoil의 전역 상태만 들어감

**Comment by algo2000** [comment]
@parkgang 올려주신 디렉터리 구조를 기본 구조로 따르며 추가적으로 필요한 폴더를 추가하여 사용하겠습니다.
