### ISSUE TITLE
@algo2000 레거시 문서 인거 같습니다. 다음 버전에 문서를 업데이트 해주세요.

### ISSUE THREAD

**Issue by parkgang** [belf-kr/front-server#35]
@algo2000 레거시 문서 인거 같습니다. 다음 버전에 문서를 업데이트 해주세요.

_Originally posted by @parkgang in https://github.com/belf-kr/front-server/pull/31#discussion_r637364238_

**Comment by algo2000** [comment]
@parkgang 정확히 어떤거를 추가하라는 말인가요?

**Comment by parkgang** [comment]
> @parkgang 정확히 어떤거를 추가하라는 말인가요?

@algo2000 `README.md` 입니다. 디렉터리 구조 같은 부분이 업데이트 되지 않아있어요. 커밋 컨벤션의 경우도 repo 단위 보다는 팀단위로 wiki에 적어놓는 것이 좋아보입니다.
